### PR TITLE
fix: rate limit does not apply to professor

### PR DESCRIPTION
**Pull request by karel-harjono**
kevin pls approve :)

### CODE REVIEW

**Comment by wskksw** [comment]
Tests are failing now for the changed end point. Need to update test cases.

**Comment by AdamFipke** [comment]
Also the populate chat token endpoint does something very different than resetting the token uses. The populate chat token looks to have been there to ensure that all users have a chat token associated with them (since i guess maybe they won't always), hence why this was an endpoint in developer settings

**Review by AdamFipke — CHANGES_REQUESTED** [review]
wohoo I have internet again and can properly request changes now

**Review by wskksw — APPROVED** [review]
I made changes to revert the old endpoint

**Comment by AdamFipke** [comment]
no tests? :((((

**Comment by wskksw** [comment]
I will be writing some today with my other branch. I needed to quickly push these to production yesterday because class started today.

**Comment by AdamFipke** [comment]
oh okay. While writing the tests, the following should also be changed:
- The backend endpoint is going to update for all users rather than just the users in the organisation. 
- Also you probably want a try catch there in case the query fails for some reason.
- Also this new endpoint you made can probably just set used to 0. If it's also resetting the max_uses, it should say as such (since not all users may have their max_uses set the same).

**Comment by wskksw** [comment]
sounds good!

**Pull request merged**
